# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi!
tagline:          'A Personal Website'
description:      'Engineering the oceans. Made by <a href="https://twitter.com/cpdis" target="_blank">@cpdis</a>.'
url:              http://cpdis.com
baseurl:          /

author:
  name:           'Colin Dismuke'
  url:            https://twitter.com/cpdis

gems:             [jekyll-paginate, jekyll-gist]
paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cpdis/
