# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hi!
tagline:          'A Personal Website'
description:      'Engineering the world's oceans.. Made by <a href="https://twitter.com/cpdis" target="_blank">@cpdis</a>.'
url:              http://cpdis.com
baseurl:          /

author:
  name:           'Colin Dismuke'
  url:            https://twitter.com/cpdis

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cpdis/blog
